In [2]:
#https://machinelearningmastery.com/return-sequences-and-return-states-for-lstms-in-keras/

In [3]:
import numpy as np
from keras.layers import Input, LSTM
from keras.models import Model

In [4]:
input = Input(shape=(3,1)) #we will hv one sample with 3 time steps
output = LSTM(1)(input)
model = Model(inputs=input,outputs=output)

In [5]:
data = np.array([0.1,0.2,0.3]).reshape(-1,3,1)  #since, input_shape is (3,1)

In [6]:
model.predict(data) #it outputs a single hidden state for an input with 3 time steps

array([[0.00435828]], dtype=float32)

**Return Sequences**

In [7]:
input = Input(shape=(3,1))
output = LSTM(1,return_sequences=True)(input)
model = Model(inputs=input,outputs=output)

model.predict(data) #it returns a sequence of 3 values, one hidden state output for each time-step of input

array([[[-0.02294573],
        [-0.06260297],
        [-0.11298669]]], dtype=float32)

**Note**

In [8]:
#you must set return_sequences = True when stacking LSTM layers so that
#the second LSTM layer has an 3 time step input, otherwise second LSTM will have a single value input

**Return States**

In [13]:
input = Input(shape=(3,1))
output,state_h,state_c = LSTM(1,return_state=True)(input)

model = Model(inputs=input,outputs=[output,state_h,state_c])

model.predict(data)

[array([[0.04164772]], dtype=float32),
 array([[0.04164772]], dtype=float32),
 array([[0.07780854]], dtype=float32)]

In [11]:
# The LSTM hidden state output for the last time step.
# The LSTM hidden state output for the last time step (again).
# The LSTM cell state for the last time step.

**Return States and Sequences**

In [15]:
input = Input(shape=(3,1))
output,state_h,state_c = LSTM(1,return_sequences=True,return_state=True)(input)
model = Model(inputs=input,outputs=[output,state_h,state_c])
model.predict(data)

[array([[[0.01718909],
         [0.04492081],
         [0.07814135]]], dtype=float32),
 array([[0.07814135]], dtype=float32),
 array([[0.17401767]], dtype=float32)]

In [16]:
#The layer returns the hidden state for each input time step,
# then separately, the hidden state output for the last time step and the cell state for the last input time step.